theme:
  # url prefix of the fetching of json data
  # api_prefix: api
  # cdn for theme statics
  # cdn:
  # body background
  background: confectionary.png \#f5f7fa
  # sidebar background
  sidebar_background: shattered-island.png
  # maximum width of content
  # content_width: 640

# language
language: zh-Hans

# Sidebar menu
menu:
  home: /
  # about: /about
  # links: /links

# Profile
profile:
  avatar: avatar.jpg
  # Email address will be used for showing gravatar(https://en.gravatar.com) avatar if `avatar` is not specified.
  email: w962961915@gmail.com
  bio: 人生的意义，在于承担人生无意义的勇气。

# Social media
# Try to sort by changing the order of the keys
sns:
  # `email` will fallback to `profile.email` if not specified
  email:
  # `feed` will fallback to `feed.path` of site if not specified
  feed:
  github: https://github.com/vincentdou
  twitter:
  facebook:
  google+:
  instagram:
  tumblr:
  dribbble:
  telegram:
  youtube:
  hangouts:
  linkedin:
  pinterest:
  soundcloud:
  myspace:
  weibo:
  qq:

footer:
  # If not defined, will show current year and author, eg: ©2018 • Superman.
  copyright:

  # Set to false to hide Hexo link.
  powered: true
  # Set to false to hide theme info.
  theme: true

  # Custom text can be defined here.
  # custom: Hosted by <a target="_blank" rel="external nofollow" href="https://pages.coding.me"><b>Coding Pages</b></a>

# Post
post:
  per_page: 10
  # Table of content, enabled by default, set to false to disable.
  toc:
    # The depth of toc, default is 2, maximum to 4.
    # depth: 3
    # Showing index before toc, eg. 1.1 title
    # index: true
  # Show reward panel
  # reward: true
  # Copyright notice
  # Disabled by default, remove the hash to enable
  # You can also use front matter `copyright` to override this setting.
  # copyright:
    # Global enable, true by default
    # global: true
    # Show author, false by default
    # author: true
    # Show post link, true by default
    # link: false
    # license: Attribution-NonCommercial-NoDerivatives 4.0 International
    #   (<a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\" rel=\"external nofollow noopener\" target=\"_blank\">CC BY-NC-ND 4.0</a>)
    # Show post date, true by default
    # published: false
    # Show post update date, false by default
    # updated: false
    # Totally custom copyright
    # custom: my copyright

# Page
page:
  # Show reward panel
  # reward: true

# Archive
archive:
  per_page: 10

# Tag
tag:
  per_page: 10

# Category
category:
  per_page: 10

# Favicon
# Default is `favicon.ico`
# favicon: favicon.ico

# Disqus comments
comments:
  # disqus:
    # shortname: your_disqus_shortname
    # Or you can set disqus script directly
    # script: //your_disqus_shortname.disqus.com/embed.js
    # Set to true to auto load disqus, otherwise will show a button
    # autoload: false

# Assets path
assets:
  # prefix: 'https://cdn.example.com'
  # suffix: '?m=webp&q=80'

# PWA
pwa:
  # Workbox(https://developers.google.com/web/tools/workbox/) is a JavaScript libraries for adding offline support to web apps
  # Disabled by default, remove the hash to enable
  # workbox:
    # Workbox cdn, uses google by default, below is an example of using alicdn
    # cdn: https://g.alicdn.com/kg/workbox/3.3.0/workbox-sw.js
    # module_path_prefix: https://g.alicdn.com/kg/workbox/3.3.0/
    # Expire time in hour, 4 by default, set to 0 to be permanent, caches will be forcibly deleted the next time the site is updated.
    # expire: 4
    # The worker script name, `sw.js` by default
    # name: sw.js
    # Custom rules
    # rules:
    #   - name: jsdelivr
    #     strategy: staleWhileRevalidate
    #     regex: https://cdn\\.jsdelivr\\.net
    #   - name: gtm
    #     strategy: staleWhileRevalidate
    #     regex: https://www\\.googletagmanager\\.com\?id=.*
    #   - name: gravatar
    #     strategy: staleWhileRevalidate
    #     regex: https://www\\.gravatar\\.com
    #   - name: theme
    #     strategy: staleWhileRevalidate
    #     regex: /.*\\.(?:js|css|woff2|png|jpg|gif)$
    #   - name: cdn
    #     strategy: staleWhileRevalidate
    #     regex: https://cdn\\.yourdomain\\.com
    #   - name: json
    #     strategy: cacheFirst
    #     regex: your_api_prefix/.*\\.json

  manifest:
    short_name:
    name:
    start_url: /blog
    theme_color: '#2a2b33'
    background_color: '#2a2b33'
    icons:
      - src: icon-194x194.jpg
        sizes: 194x194 512x512
        type: image/jpg
      - src: icon-144x144.jpg
        sizes: 144x144
        type: image/jpg

# SEO
seo:
  # Render structured-data
  # Disabled by default, set to true to enable
  # structured_data: true

# Reward
# qrcode: url of the qrcode images, optional
# url: link of the payment, optional
# text: text of the url, url will be displayed as default
# You must set either a qrcode or a url
# reward:
#   methods:
#     - name: wechat
#       qrcode:
#       url:
#       text:
#     - name: alipay
#       qrcode:
#       url:
#       text:
#     - name: paypal
#       qrcode:
#       url:
#       text:
#     - name: bitcoin
#       qrcode:
#       url:
#       text:

# Google analytics
# ga: UA-00000000-0
